### ISSUE TITLE
Run in subdirectory

### ISSUE THREAD

**Issue by MarekSuchanek** [MarekSuchanek/repocribro#5]
Find a way how to deploy repocribro in subdirectory and not root of domain (e.g. http://example.xyz/repocribro/)!

**Comment by MarekSuchanek** [comment]
Looks like I need to do something ugly like this: http://flask.pocoo.org/snippets/35/

**Comment by hroncok** [comment]
That depends on the webserver, doesn't it?

**Comment by MarekSuchanek** [comment]
Problem was with the absence of subdirectory in paths generated by `url_for`. It can be solved with `DispatcherMiddleware` according to https://stackoverflow.com/questions/18967441/add-a-prefix-to-all-flask-routes. Just setting `APPLICATION_ROOT` is not enough for flask (it will only limit session cookies path). I'm going to include check if `APPLICATION_ROOT` is set in order to use `DispatcherMiddleware` appropriately.

**Comment by MarekSuchanek** [comment]
Solved with #6
